name: validations
description: Validations for dart models.
version: 0.8.5
homepage: https://github.com/dartlib/validations.git
author: Rob Halff <rob.halff@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  decimal: ^2.3.2
  meta: ^1.9.1
  intl: ^0.18.0
  validators: ^3.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  coverage: ^1.6.3
  build_runner: ^2.3.3
  validations_generator:
    path: ../validations_generator
  lints: ^2.0.1
  test: ^1.24.0
