name: validations_generator
version: 0.8.4
description: Generator for the validations package.
authors:
  - Rob Halff <rob.halff@gmail.com>
homepage: https://github.com/dartlib/validations.git

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  validations:
    path: ../validations
  analyzer: ^5.10.0
  build: ^2.3.1
  build_config: ^1.1.1
  logging: ^1.1.1
  source_gen: ^1.2.7
  code_builder: ^4.4.0
  dart_style: ^2.3.0
  meta: ^1.9.1

dev_dependencies:
  decimal: ^2.3.2
  lints: ^2.0.1
  test: ^1.24.0
  build_runner: ^2.3.3
  intl: ^0.18.0
  build_test: ^2.1.7
  collection: ^1.17.1
